### ISSUE TITLE
CT all returned solveCubicRootsReal roots should be finite

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/kite#89]
```
kite : top-level-unit-tests : unbuilt?ea
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/kite-tests.html?ea
32 out of 33 tests passed. 1 failed.
Shape: CAG multiple test failed:
Died on test phetsims/least-squares-regression#1 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/ShapeTests.js:214:7: Assertion failed: All returned solveCubicRootsReal roots should be finite
Error: Assertion failed: All returned solveCubicRootsReal roots should be finite
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/dot/js/Utils.js:489:47
at Array.forEach (<anonymous>)
at solveCubicRootsReal (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/dot/js/Utils.js:489:30)
at Cubic.intersection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/segments/Cubic.js:807:16)
at Function.intersectOther (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/segments/Line.js:700:36)
at Function.intersect (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/segments/Segment.js:729:24)
at Graph.eliminateIntersection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/ops/Graph.js:694:41)
at Graph.computeSimplifiedFaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/ops/Graph.js:189:10)
at Function.binaryResult (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/ops/Graph.js:1286:11)

id: Bayes Chrome
Snapshot from 8/31/2021, 7:12:47 AM

----------------------------------

kite : top-level-unit-tests : unbuilt?ea&brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/kite-tests.html?ea&brand=phet-io
32 out of 33 tests passed. 1 failed.
Shape: CAG multiple test failed:
Died on test phetsims/least-squares-regression#1 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/ShapeTests.js:214:7: Assertion failed: All returned solveCubicRootsReal roots should be finite
Error: Assertion failed: All returned solveCubicRootsReal roots should be finite
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/assert/js/assert.js:25:13)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/dot/js/Utils.js:489:47
at Array.forEach (<anonymous>)
at solveCubicRootsReal (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/dot/js/Utils.js:489:30)
at Cubic.intersection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/segments/Cubic.js:807:16)
at Function.intersectOther (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/segments/Line.js:700:36)
at Function.intersect (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/segments/Segment.js:729:24)
at Graph.eliminateIntersection (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/ops/Graph.js:694:41)
at Graph.computeSimplifiedFaces (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/ops/Graph.js:189:10)
at Function.binaryResult (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1630415567352/kite/js/ops/Graph.js:1286:11)

id: Bayes Chrome
Snapshot from 8/31/2021, 7:12:47 AM
```

**Comment by samreid** [comment]
Assigning to responsible dev for initial triage.

**Comment by jonathanolson** [comment]
I can trigger this with `dot.Utils.solveCubicRootsReal( -25.86251423252329, 41.33125272769773, 7.276667189056057,0.30451846343605116 )`.

**Comment by jonathanolson** [comment]
@KatieWoe I believe this (and hopefully other cases) should be fixed by the above commit. Can you let me know if it shows up after?

**Comment by KatieWoe** [comment]
Looks solved in CT
